#!/usr/bin/env php
<?php
/**
 * Updating docset
 * @author bravepickle <2bravepickle@gmail.com
 * @license MIT
 */
require 'vendor/autoload.php';

$lang = 'en';
$filename = 'current.html';
$url = 'http://sphinxsearch.com/docs/' . $filename;
$destDir = dirname(__FILE__) . '/var/Sphinx.docset';
$filesDir = dirname(__FILE__) . '/files';

$indexFile = 'sphinxsearch.com/docs/' . $filename;

$resDir = "$destDir/Contents/Resources/Documents";

exec("rm -rf $resDir");
exec("mkdir -p $resDir");
exec("wget -q -F -p -P $resDir -k --reject \"*.js,*.txt\" $url");
exec("cp $filesDir/icon.png $destDir/icon.png");

$plist = <<<HEREDOC
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleIdentifier</key>
	<string>sphinxsearch-{$lang}</string>
	<key>CFBundleName</key>
	<string>Sphinx</string>
	<key>DocSetPlatformFamily</key>
	<string>sphinxsearch</string>
	<key>isDashDocset</key>
	<true/>
	<key>dashIndexFilePath</key>
	<string>$indexFile</string>
</dict>
</plist>
HEREDOC;

file_put_contents("$destDir/Contents/Info.plist", $plist);

$db = new sqlite3("$destDir/Contents/Resources/docSet.dsidx");
$db->query("DROP TABLE IF EXISTS searchIndex");
$db->query("CREATE TABLE searchIndex (id INTEGER PRIMARY KEY, name TEXT, type TEXT, path TEXT)");
$db->query("CREATE UNIQUE INDEX anchor ON searchIndex (name, type, path)");

$urlPrefix = 'sphinxsearch.com/docs/';
$crawler = new Symfony\Component\DomCrawler\Crawler();
$crawler->addHtmlContent(file_get_contents("$resDir/sphinxsearch.com/docs/current.html"));
$els = $crawler->filter('.toc dl a');

/** @var \DOMElement $el */
foreach ($els as $el) {
    $db->query("INSERT OR IGNORE INTO searchIndex(name, type, path) VALUES (\"$el->textContent\",\"Guide\",\"${urlPrefix}{$el->getAttribute('href')}\")");
}
