#!/usr/bin/env php
<?php
/**
 * Updating docset
 * @author bravepickle <2bravepickle@gmail.com
 * @license MIT
 */
require 'vendor/autoload.php';
require 'functions.php';

$lang = 'en';
$filename = 'current.html';
$url = 'http://sphinxsearch.com/docs/' . $filename;
$destDir = dirname(__FILE__) . '/var/Sphinx.docset';
$filesDir = dirname(__FILE__) . '/files';
$indexFile = 'sphinxsearch.com/docs/' . $filename;
$resDir = "$destDir/Contents/Resources/Documents";
$urlPrefix = 'sphinxsearch.com/docs/';

updateDocFiles($resDir, $url, $filesDir, $destDir);
initPlistConfig($lang, $indexFile, $destDir);
$db = initDb($destDir);
$crawler = parseHtmlFile($resDir, $urlPrefix, $filename);
addGuides($crawler, $db, $urlPrefix);
addFunctions($resDir, $db, $urlPrefix);
